name: tutorial1
version: 1.0.0
description: startup polymerize project
dependencies:
 polymerize: ^0.9.4
 polymer_element: ^2.0.5
 logging: any
 intl: any
 html5: ^0.1.7
web:
 compiler:
  release: dartdevc
  debug: dartdevc
transformers:
  - polymerize:
     entry-points:
       - web/*.dart
